name: CI pipe

on:
  push:
    branches:
      - main
      - prelease
      - development

  pull_request:
    branches:
      - main
      - prelease
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm run lint    
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run build
        
      - name: Test
        run: pnpm run test:unit

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Cypress Install
        run: npx cypress install --force  
      - name: Run cypress test
        uses: cypress-io/github-action@v4
        with:
          start: node scripts/before-e2e.js
          wait-on: 'http://localhost:5001,http://localhost:5002,http://localhost:5003,http://localhost:5004'
          wait-on-timeout: 600
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}